// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var services = [
  {
    slug: "paid-ads",
    name: "Paid Ads (Meta & Google)",
    price_cad_monthly: 759,
    url: "https://ap-digital.ca/services/paid-ads"
  },
  {
    slug: "social-media",
    name: "Social Media Management",
    price_cad_monthly: 849,
    url: "https://ap-digital.ca/services/social-media"
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the digital marketing services AP Digital offers with monthly CAD pricing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services, currency: "CAD" }
  })
});

// src/lib/mcp/tools/list-locations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var locations = [
  "Vancouver",
  "Surrey",
  "Burnaby",
  "Richmond",
  "Langley",
  "Coquitlam",
  "Abbotsford"
].map((city) => ({
  city,
  url: `https://ap-digital.ca/${city.toLowerCase()}`
}));
var list_locations_default = defineTool2({
  name: "list_locations",
  title: "List service locations",
  description: "List the BC cities/regions AP Digital serves with dedicated pages.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(locations, null, 2) }],
    structuredContent: { locations }
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var pricing = [
  {
    service: "Paid Ads",
    price_cad_monthly: 759,
    description: "Meta & Google ad campaigns \u2014 built, managed, and optimized. Ad spend billed separately by Google/Meta.",
    url: "https://ap-digital.ca/services/paid-ads"
  },
  {
    service: "Social Media Management",
    price_cad_monthly: 849,
    description: "2 platforms managed, 12 custom posts/month, captions, scheduling, and community management.",
    url: "https://ap-digital.ca/services/social-media"
  }
];
var get_pricing_default = defineTool3({
  name: "get_pricing",
  title: "Get pricing",
  description: "Return AP Digital's per-service monthly pricing (CAD). Month-to-month, no long-term contracts, 90-day results guarantee.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(pricing, null, 2) }],
    structuredContent: {
      pricing,
      currency: "CAD",
      contract: "month-to-month",
      guarantee: "90-day results guarantee",
      pricing_page: "https://ap-digital.ca/pricing"
    }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return AP Digital's contact channels and booking link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: "Email: apdigital.core@gmail.com\nPhone: +1-778-682-5772\nBook a call: https://calendly.com/apdigital-core/20min" }],
    structuredContent: {
      email: "apdigital.core@gmail.com",
      phone: "+1-778-682-5772",
      booking_url: "https://calendly.com/apdigital-core/20min",
      website: "https://ap-digital.ca"
    }
  })
});

// src/lib/mcp/index.ts
var projectRef = "pgivuezbonyqqbaazfnp";
var mcp_default = defineMcp({
  name: "ap-digital-mcp",
  title: "AP Digital MCP",
  version: "0.1.0",
  instructions: "Tools for AP Digital, a Vancouver, BC digital marketing agency. Use these tools to look up services, service locations, pricing tiers, and contact/booking info.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, list_locations_default, get_pricing_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
